### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Shiuan-Chang**
Hi cwpeng,

My name is 張瑞璇，my discord name is RSChang. The following link is my task this week. 
If you have any suggestion, please do not hesitate to tell me.

http://34.225.66.108:3000/

Regards

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by Shiuan-Chang** [comment]
Hi cwpeng,

I apologize for providing the wrong link earlier. I've checked and adjusted my security groups on AWS, and now it seems to work. I've tested the link on my cell phone and another computer. Hope everything goes well this time.

http://34.225.66.108:3000/

Regards
瑞璇

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Shiuan-Chang** [comment]
Thanks!

**Pull request merged**
