### PR TITLE
12th commit

### PR DESCRIPTION
**Pull request by Shiuan-Chang**
Hi cwpeng,

I hope all is well with you.

My name is 張瑞璇，and my discord account is RSChang.

Below are the links to this week's tasks. I recognize that the Media Queries between 601px-1200px could be refined further. I'll be sending you an improved version. If you have any suggestions or feedback, please feel free to share. Thank you.

1. http://34.225.66.108:3000/
2. http://34.225.66.108:3000/attraction/7

Regards
RSChang

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Second separating line should be 1px height only.

**Comment by Shiuan-Chang** [comment]
Hi cwpeng,

My name is 張瑞璇，and my discord account is RSChang.

The new links are as below. I made some adjustments. If you have any suggestions or feedback, please feel free to share. Thank you.

1. http://34.225.66.108:3000/
2. http://34.225.66.108:3000/attraction/7


Regards
RSChang

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Shiuan-Chang** [comment]
Thanks!

**Pull request merged**
