### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Shiuan-Chang**
彭彭老師晚安：
我是瑞璇，discord名字是RSChang。以下是我這次作業的網址，請老師檢查，謝謝老師！
http://34.225.66.108:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but we have 1px border for each attraction box.

**Comment by Shiuan-Chang** [comment]
Hi cwpeng,

I am RSChang in wehelp discord group. I modified the the border you mentioned. 

You can check the following link to review my website.  
http://34.225.66.108:3000/

If there is anything to be fixed, please do not hesitate to message me. Thanks.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Good. But another awaring issue is that we have to implement **scrolling animation effect** on MRT list when we click on arrows.

**Comment by Shiuan-Chang** [comment]
Hi cwpeng,
I added scroll-behavior property in my CSS, ensuring a smoother scrolling experience for the MRT list when the arrow buttons are clicked. You can find the link below. Should there be any other issues, I would greatly appreciate your feedback. Thank you!
http://34.225.66.108:3000/

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Shiuan-Chang** [comment]
thanks!

**Pull request merged**
